[package]
name = "hrpg"
description = "Human Readable Parser Generator"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = { version = "3.0.0-rc.4", features = ["derive"] }
convert_case = "0.4"
pest = "2"
pest_derive = "2"
railroad = "0.1"
