[package]
name = "hrpg"
description = "Human Readable Parser Generator"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = "3.0.0-beta.4"
pest = "2.1.3"
pest_derive = "2.1.0"
convert_case = "0.4.0"
railroad = "0.1.1"
