[package]
name = "parser"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[workspace]

[dependencies]
convert_case = "0.4.0"
quote = "1.0.9"
syn = { version = "1.0.77", features = ["full"] }
proc-macro2 = "1.0.29"
